# examples:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_cleanup_with_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day

default: &default
  sweep_stale_devices:
    class: SweepStaleDevicesJob
    schedule: every 30 seconds

  ai_usages_cleanup:
    class: AiUsagesCleanupJob
    schedule: every day at 3am

  ai_sessions_orphan_sweep:
    class: AiSessionsSweeperJob
    schedule: every 5 minutes

development:
  <<: *default

production:
  <<: *default
  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12
